style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/KadVenku/eaw-dtac
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - refactor
        - chore
        - ci
    sort_by: Scope
  commit_groups:
    group_by: Type
    sort_by: Title
    title_maps:
      feat: Features
      fix: Bug Fixes
      refactor: Code Refactoring
      chore: Other Changes
      ci: CI/CD Pipeline Changes
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - #
  refs:
    actions:
      - Closes
      - Fixes
      - Implements     
  notes:
    keywords:
      - BREAKING CHANGE