name: NetFramework.CI.Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - name: Restore NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest
      run: nuget restore eaw-dtac.sln
    - name: Build .NET
      run: dotnet build --configuration Debug
