name: NetFramework.CI.Build

on: [push]

jobs:
  build-debug:
    name: Build (Debug Config)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore Packages
      run: nuget restore eaw-dtac.sln
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild eaw-dtac.sln -p:Configuration=Debug
