name: NetFramework.CI.Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-verison: 2.2.108
    - name: Build .NET
      run: dotnet build --configuration Debug
